name: test disparity
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Setup env
        uses: ./.github/actions/setup-env
        with:
          riscv_gnu_toolchain_hash: ${{ inputs.riscv_gnu_toolchain_hash }}
          free_up_space: true
          
      - name: python version check
        run: |
          which python
          which python3
          which pip
          which pip3
          pip install -r requirements.txt
          python ./riscv-gnu-toolchain/scripts/download_artifact.py -name 39099-v2_Improve_vsetvl_vconfig_alignment-1-downloaded-patches -repo ewlu/gcc-precommit-ci -token ${{ secrets.GITHUB_TOKEN }} -outdir ./patches
          ls patches
          unzip patches/39099-v2_Improve_vsetvl_vconfig_alignment-1-downloaded-patches

