name: test disparity
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: python version check
        run: |
          which python
          which python3
          which pip
          which pip3
