name: test gist
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  compare-artifacts:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        run: |
          git submodule update --init riscv-gnu-toolchain

      - name: test gist step
        run: |
          touch test.log
          echo "This is a test gist" >> test.log
          python3 -m pip install pygithub requests pyopenssl --upgrade
          python3 ./scripts/create_gist.py --token ${{ secrets.GIST_TOKEN }} --input test.log --output url.log --title "hi gcc 0293c c.log"
          cat url.log
